import Link from 'next/link';
import './globals.css';
import { UIProvider } from './theme';
import { AuthComponent } from '@/components/auth/AuthComponent';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className='min-h-screen flex flex-col'>
        <UIProvider>
          <header className='h-14 min-w-full p-2 flex flex-row justify-between items-center border-b-[1px] border-b-black'>
            <Link href='/' className='font-extrabold text-3xl'>
              Taboo.AI
              <span className='font-light text-base ml-2'>For Teacher</span>
            </Link>
            <AuthComponent />
          </header>
          <section className='flex flex-row min-w-full h-auto flex-grow'>
            <nav className='min-w-[150px] border-r-[1px] border-r-black'>
              Navigation Panel
            </nav>
            <main>{children}</main>
          </section>
          <footer className='min-w-full h-8 border-t-[1px] border-t-black'>
            Footer
          </footer>
        </UIProvider>
      </body>
    </html>
  );
}
